A=rand(3);
A=A'*A;
writematrix(A,"rand3.txt")
A=rand(5);
A=A'*A;
writematrix(A,"rand5.txt")
A=rand(10);
A=A'*A;
writematrix(A,"rand10.txt")
A=rand(100);
A=A'*A;
writematrix(A,"rand100.txt")
A=rand(300);
A=A'*A;
writematrix(A,"rand300.txt")
A=hilb(3);
writematrix(A,"hilb3.txt")
A=hilb(5);
writematrix(A,"hilb5.txt")
A=hilb(10);
writematrix(A,"hilb10.txt")
A=hilb(100);
writematrix(A,"hilb100.txt")
A=hilb(300);
writematrix(A,"hilb300.txt")